import { createPublicClient, encodeFunctionData, http, type Abi, type Address } from "viem";
import { readFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import { chains } from "../config/chains";
import { CompositeAbiResolver, EvmContractAbiInspector } from "../src/discovery/contract/abi-source";
import { EvmEligibilityInspector } from "../src/discovery/contract/eligibility";
import { EvmClaimInspector } from "../src/discovery/contract/claims";
import { DefaultCalldataBuilder } from "../src/discovery/contract/detector";
import { RpcSimulator } from "../src/simulation/rpc";
import { DefaultPolicyEngine } from "../src/execution/policy";
import { DefaultOpportunityEngine } from "../src/core/opportunity";
import { RuleClassifier } from "../src/core/classifier";
import type { MintCandidate, SimulationResult } from "../src/domain/types";

const chainKey = process.env.TESTNET_CHAIN_KEY ?? "base";
const config = chains[chainKey];
if (!config) throw new Error(`Unknown TESTNET_CHAIN_KEY: ${chainKey}`);
const rpcUrl = process.env.TESTNET_RPC_URL || process.env[config.rpcEnv];
const contract = process.env.TESTNET_CONTRACT as Address | undefined;
const from = (process.env.TESTNET_FROM || process.env.SIMULATION_FROM) as Address | undefined;
if (!rpcUrl || !contract || !from) throw new Error("Set TESTNET_RPC_URL, TESTNET_CONTRACT, and TESTNET_FROM (or SIMULATION_FROM)");
const client = createPublicClient({ transport: http(rpcUrl) });
const chainId = await client.getChainId();
if (chainId !== config.chainId) throw new Error(`RPC chain mismatch: expected ${config.chainId}, got ${chainId}`);
const candidate: MintCandidate = { id: `testnet-probe-${Date.now()}`, chainKey, contract, source: "testnet-probe", discoveredAt: new Date().toISOString(), mintFunction: process.env.TESTNET_MINT_FUNCTION, valueWei: 0n, from, metadata: { assetType: "nft", probe: true } };
const explorerApi = chainKey === "base" ? "https://base.blockscout.com/api" : chainKey === "ethereum" ? "https://eth.blockscout.com/api" : undefined;
const resolver = new CompositeAbiResolver({ explorer: explorerApi, explorerChainParam: String(chainId), explorerApiKey: process.env.EXPLORER_API_KEY }).resolve.bind(new CompositeAbiResolver({ explorer: explorerApi, explorerChainParam: String(chainId), explorerApiKey: process.env.EXPLORER_API_KEY }));
const abiInspector = new EvmContractAbiInspector([rpcUrl], resolver);
const eligibilityInspector = new EvmEligibilityInspector([rpcUrl], from);
const claimInspector = new EvmClaimInspector();
let inspected = await abiInspector.inspect(candidate);
inspected = await eligibilityInspector.inspect(inspected);
inspected = await claimInspector.inspect(inspected);
const abi = inspected.metadata.abi as unknown as Abi | undefined;
const requestedFunction = process.env.TESTNET_MINT_FUNCTION;
const rawArgs = (process.env.TESTNET_MINT_ARGS ?? "").split(",").filter((value) => value.length > 0);
const args = rawArgs.map((value) => value === "true" ? true : value === "false" ? false : value.startsWith("0x") ? value : /^\d+$/.test(value) ? BigInt(value) : value);
let data: `0x${string}` | undefined;
if (abi && requestedFunction) data = encodeFunctionData({ abi, functionName: requestedFunction, args }) as `0x${string}`;
else if (requestedFunction) data = (await new DefaultCalldataBuilder().build({ ...inspected, mintFunction: requestedFunction, calldata: undefined })).data;
if (!data) throw new Error("Unable to construct calldata; provide a verified ABI and TESTNET_MINT_FUNCTION/TESTNET_MINT_ARGS");
const finalCandidate = { ...inspected, calldata: data };
const request = { chainKey, to: contract, data, value: 0n, from };
let simulation: SimulationResult;
try { simulation = await new RpcSimulator({ [chainKey]: client }).simulate(finalCandidate, request); } catch (error) { simulation = { success: false, stateDiffAvailable: false, assetDiff: [], approvalDiff: [], revertReason: String(error), metadata: { simulationMode: "rpc" } }; }
const classification = await new RuleClassifier().classify(finalCandidate, simulation);
const opportunity = await new DefaultOpportunityEngine().score(finalCandidate, classification, simulation);
const decision = await new DefaultPolicyEngine().evaluate(opportunity, simulation);
const report = { chainKey, chainId, contract, from, request: { ...request, value: request.value.toString() }, metadata: finalCandidate.metadata, simulation, classification, opportunity, decision, generatedAt: new Date().toISOString(), execution: "not connected; no signature or broadcast" };
const output = process.env.TESTNET_REPORT ?? "data/testnet-probe.json";
await mkdir(dirname(output), { recursive: true });
await Bun.write(output, JSON.stringify(report, (_, value) => typeof value === "bigint" ? value.toString() : value, 2));
console.log(JSON.stringify({ report: output, policy: decision.allowed ? "PASS" : opportunity.expectedValueNative <= 0 ? "SKIP" : "REJECT", simulation: simulation.success, calldata: data, execution: "not connected" }, null, 2));
